name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUBLIC_TOKEN }}
          submodules: true
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
      - name: Build the server
        run:
          ./gradlew build
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
          IMAGE_NAME: ${{secrets.DOCKER_HUB_USERNAME}}/${{ vars.REPOSITORY_NAME }}
          TAG_NAME: ${{ env.GITHUB_SHA }}
          BUILDX: "true"